learning_platform/views/users.py
import os
import io
from datetime import datetime, timedelta
import requests
from flask import (
    Blueprint, render_template, redirect, url_for, request, jsonify, flash, session, send_file)
from botocore.exceptions import ClientError
from flask_babel import gettext as _
from flask_limiter.errors import RateLimitExceeded
from flask_login import login_required, current_user, logout_user, login_user
from flask_mail import Message
from learning_platform import bcrypt, db, app, mail, limiter
from learning_platform.forms.form import Registration, LoginForm, ResetForm, NewPasswordForm
from learning_platform.models.models import User, Course, SubTopic, User_solution
from learning_platform.google_translations import text_translator
from learning_platform._helpers import (
    c_and_topics, cached, validate_time_task, get_ref, get_lang, presigned_url,
    presigned_cert_url, upload_certificate, s3_client, encryption, verify_payment, completed_course)
from PIL import Image, ImageDraw, ImageFont

user_bp = Blueprint('users', __name__, static_folder='static',
                    template_folder='templates')


ref = []


def cert_available(key):
    s3 = s3_client()
    cert = f'{encryption("cert")[:16]}'
    try:
        s3.get_object(Bucket=cert, Key=key)
    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchKey':
            return False
    return True


def pop_ref():
    for i, v in enumerate(ref):
        ref.pop(i)


def user_enrolled_courses(course_id):
    if not current_user.is_authenticated:
        flash(_('please login first'), category='info')
        return redirect(url_for('home.home'))
    user_courses = current_user.enrolling
    for c in user_courses:
        if c.id == course_id:
            return True, c
    return False, None


def completed_topics(c):
    user = current_user
    all = 0
    some = 0
    for u in c.time_task.sub_topic:
        all += 1
        for t in user.user_solu.sub_topics:
            if u.name_a == t.name_a:
                some += 1
                break
    return int((some / all) * 100)


@user_bp.errorhandler(RateLimitExceeded)
def rateLimit_handler(e):
    return jsonify(error='something went wrong. try again')


@user_bp.route('/register', methods=['GET', 'POST'])
def register():
    l = 'This name will appear on your certificate when you enroll in a course'
    lang = get_lang()
    if lang != "en":
        l = text_translator(l, lang)

    form = Registration(request.form)
    if form.validate_on_submit():
        fullname = form.fullname.data
        username = form.username.data
        email = form.email.data
        moderator = False
        hashed_password = bcrypt.generate_password_hash(form.password.data)

        if not User.query.filter_by(email=email).first():
            user = User(fullname=fullname, username=username, email=email,
                        password=hashed_password, moderator=moderator)

            user.user_solu = User_solution(user=user)
            db.session.add(user)
            db.session.commit()
            if moderator:
                flash(
                    f"you have successfully registered {fullname} as admin",
                    category='success')
            else:
                flash(_("Thank you for Registering"), category='success')
        return redirect(url_for('users.login'))
    return render_template('user/register.html', form=form, l=l)


@user_bp.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        try:
            if user and bcrypt.check_password_hash(
                    user.password, form.password.data):
                user.authenticated = True
                db.session.add(user)
                db.session.commit()
                login_user(user)
                next = request.args.get(
                    'next_url') or url_for('users.userprofile')
                flash(_('Happy Coding!  😊'), category='success')
                return redirect(next)
            flash(_("Invalid Credentials"), category='warning')
            return redirect(url_for('users.login'))
        except BaseException:
            return redirect(url_for('users.login'))

    return render_template('user/login.html', form=form)


@user_bp.route("/logout", methods=['GET', 'POST'])
@login_required
def user_logout():
    '''the user will log out from here
    '''
    if not current_user.is_authenticated:
        return redirect(url_for('home.home'))
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    return redirect(url_for('home.home'))


@user_bp.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    form = ResetForm()
    if form.validate_on_submit():
        email = form.email.data
        user = User.query.filter_by(email=email).first()

        lnk_ms = 'Click this link to reset your password'
        if get_lang() != 'en':
            lnk_ms = text_translator(lnk_ms, get_lang())

        if user:
            token = get_ref()
            user.reset_token = token
            db.session.commit()
            msg = Message(_('Password Reset Request'),
                          sender='skildemycontact@gmail.com',
                          recipients=[email])
            msg.body = f'''
            {lnk_ms}
            {url_for('users.reset_password', token=token, _external=True)}
            '''
            mail.send(msg)

            flash(_('Check your email for the password reset link.'),
                  category='success')
        else:
            flash(_('Email not found'), category='danger')
            return redirect(url_for('users.login'))
    return render_template(
        'user/reset_password.html',
        form=form,
        title='Reset Password')


@user_bp.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    form = NewPasswordForm()
    user = User.query.filter_by(reset_token=token).first()
    if user:
        if request.method == 'POST':
            new_password = request.form['password']
            user.set_password(new_password)
            user.reset_token = None
            db.session.commit()
            flash(_('successfully reset password'))
            return redirect(url_for('users.login'))
    return render_template('user/reset_password_confirm.html', form=form)


@user_bp.route('/enrol/<string:course_id>', methods=['GET', 'POST'])
@login_required
def enroll_course(course_id):
    '''the student will enroll in the course
    '''
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))
    status, result = verify_payment(ref[0])

    if status:
        course = Course.query.get(course_id)

        price = course.price
        rate = course.rate
        if result['amount'] > rate * price * 65:

            mes = _('You have successfully enrolled in', category='success')
            for c in current_user.enrolling:
                if c == course:
                    c.update_enrolled_at(datetime.now())
                    mes = _('You have successfully updated your course')
                    break
            else:
                course.update_enrolled_at(datetime.now())
                current_user.enrolling.append(course)
            db.session.commit()

            flash(
                f'{mes} {course.name}', category='info')
            return render_template('payment/success.html')
    else:
        flash(
            _('unsuccessful, please check your details or contact SKILdemy support'),
            category='info')
        return render_template('payment/unsuccessful.html')


@user_bp.route("/userprofile", methods=['GET', 'POST'])
def userprofile():
    '''this will initiate the user profile setting
    '''
    if not current_user.is_authenticated:
        next_url = request.url
        return redirect(url_for('users.login', next_url=next_url))
    

    _lis = []
    user_courses = current_user.enrolling
    for c in user_courses:
        st, v = completed_course(c)
        pct = completed_topics(c)

        if v >= 0:
            ms = text_translator(str(v) + ' days left', get_lang())
            _lis.append([c, ms, pct])
        else:
            _lis.append([c, ' ', pct])

    return render_template('user/profile.html',
            user_courses=_lis)


@user_bp.route('/next_page/<int:page>/<int:fp>/<int:lp>',
               methods=['GET', 'POST'])
def paginate(page, fp, lp):
    '''the topics will be paginated here
    '''
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))

    fk = session.get('c')
    fv = session.get('dict')

    return render_template(
        'user/learn_page.html',
        fk=fk,
        fv=fv,
        page=str(page),
        fp=fp,
        lp=lp)


@user_bp.route('/learns/<string:course_id>', methods=['GET', 'POST'])
def learn_skills(course_id):
    '''the course and topics will be displayed for the
    '''
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))

    status, course = user_enrolled_courses(course_id)
    if not status:
        return redirect(url_for('users.login'))
    
    compl_c, n_ = completed_course(course)
    if compl_c:
                flash(
                    _('Please your time period to access this course has elapsed'),
                    category='warning')
                flash(
                    _('You can always extend the time without losing your current records'),
                    category='info')
                return redirect(url_for('users.userprofile'))
   
    c_and_t = c_and_topics(course)
    first_key, first_value = next(iter(c_and_t.items()))
    dict_val = {}
    for i, j in enumerate(first_value):
        dict_val[str(i)] = j

    session['dict'] = dict_val
    session['c'] = first_key
    page = '0'

learning_platform/templates/payment/payment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>
        {% block title %}
        SKILdemy
        {% endblock %}
    </title>
    
</head>
<body>
    {% block main %}
    <p class="text-light  fs-3">
        {{_('You are about to make a payment to enroll in')}} 
        <span class="btn btn-primary">
            {{c_name}}
        </span>
     </p>


       
        
        <div class="form-submit">
          <button class="bg-dark" type="submit" onclick="payWithPaystack()">
            <a class=" fs-3">
                {{_('click here to proceed to payment page')}}
            </a>
        </button>
        </div>
     
        <script src="https://js.paystack.co/v1/inline.js"></script>
    <script>
        function payWithPaystack() {
            let currency = 'GHS';
            let plan = '';
            let amount = '{{amount}}';
            let ref = '{{ref}}';
            let obj = {
                key: '{{pk}}',
                email: '{{email}}',
                currency: currency,
                amount: amount,
                ref: ref,
                callback: function(response){
                    window.location.href  = "{{url_for('users.enroll_course', course_id=c_id)}}"

                },
            };

            let handler = PaystackPop.setup(obj)
            handler.openIframe();

        }
    </script>

    {% endblock %}
</body>
</html>

learning_platform/templates/payment/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>
        {% block title %}
        SKILdemy
        {% endblock %}
    </title>
</head>
<body>
    {% block main %}
    <a style="text-decoration: none; padding: 1rem;" href="{{url_for('users.userprofile')}}" class="btn btn-info">
        Go to course
    </a>
    <div style="background-color: white;">
        <p class="text-success">{{_('Thank you for choosing SKILdemy')}}</p>
    <p class="text-success" >{{_('You can now access the course content')}}</p>
    </div>
    {% endblock %}
</body>
</html>

learning_platform/templates/payment/unsuccessful.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>
        {% block title %}
        SKILdemy
        {% endblock %}
    </title>
</head>
<body>

    {% block main %}
    <p class="text-success">{{_('payment is unsuccessful')}}</p>
    <p class="text-success">{{_('Verify your details or contact paystack')}}</p>

    {% endblock %}
    
</body>
</html>