learning_platform/views/Home.py
from flask import Blueprint, render_template, session
from flask_babel import gettext
from flask_login import current_user
from learning_platform import db
from learning_platform.google_translations import text_translator
from learning_platform.models.models import Course
from learning_platform._helpers import exchange_rate, time_, get_lang, auth_,free_trial, encryption

home_bp = Blueprint(
    'home',
    __name__,
    static_folder='static',
    template_folder='templates')


@home_bp.route('/')
def home():
    '''the page visited when the site is visited
    '''
    welc = gettext('Welcome to SKILdemy')
    courses = Course.query.all()

    status, t = time_()
    
    if status:
        rate = exchange_rate()
        for c in courses:
            c.update(t)
            c.rate = rate
        db.session.commit()

    auth = auth_()
    lang = get_lang()
    lang = lang + '.jpg'
   
    return render_template(
        'home/home.html',
        courses=courses,
        auth=auth, lang=lang, welc=welc)


@home_bp.route('/<string:course_id>/', methods=["GET"])
def home_(course_id):
    '''the page visited when a course is clicked'''
    auth = auth_()
    lang = get_lang()
    lang = lang + '.jpg'
    course = Course.query.get(course_id)
    
    if course is not None:
        desc = course.description
        if get_lang() != 'en':
            desc = text_translator(desc, get_lang())  
        trial = course.trial_topics
        free = free_trial(trial)
        topics = course.topics
        return render_template(
            'home/home.html',
            desc=desc,
            tr=free,
            topics=topics,
            course=course,
            lang=lang,
            auth=auth)
    return render_template(
        'home/home.html',
        course=course,
        lang=lang,
        auth=auth)

learning_platform/views/home.py
from flask import Blueprint, render_template, session
from flask_babel import gettext
from flask_login import current_user
from learning_platform import db
from learning_platform.google_translations import text_translator
from learning_platform.models.models import Course
from learning_platform._helpers import exchange_rate, time_, get_lang, auth_,free_trial, encryption

home_bp = Blueprint(
    'home',
    __name__,
    static_folder='static',
    template_folder='templates')


@home_bp.route('/')
def home():
    '''the page visited when the site is visited
    '''
    welc = gettext('Welcome to SKILdemy')
    courses = Course.query.all()

    status, t = time_()
    
    if status:
        rate = exchange_rate()
        for c in courses:
            c.update(t)
            c.rate = rate
        db.session.commit()

    auth = auth_()
    lang = get_lang()
    if lang == None:
        lang = 'en'
    lang = lang + '.jpg'
   
    return render_template(
        'home/home.html',
        courses=courses,
        auth=auth, lang=lang, welc=welc)


@home_bp.route('/<string:course_id>/', methods=["GET"])
def home_(course_id):
    '''the page visited when a course is clicked'''
    auth = auth_()
    lang = get_lang()
    if lang == None:
        lang =  'en'
    lang = f'{lang}.jpg'
    course = Course.query.get(course_id)
    
    if course is not None:
        desc = course.description
        if get_lang() != 'en':
            desc = text_translator(desc, get_lang())  
        trial = course.trial_topics
        free = free_trial(trial)
        topics = course.topics
        return render_template(
            'home/home.html',
            desc=desc,
            tr=free,
            topics=topics,
            course=course,
            lang=lang,
            auth=auth)
    return render_template(
        'home/home.html',
        course=course,
        lang=lang,
        auth=auth)

learning_platform/views/users.py
import os
import io
from datetime import datetime, timedelta
import requests
from flask import (
    Blueprint, render_template, redirect, url_for, request, jsonify, flash, session, send_file)
from botocore.exceptions import ClientError
from flask_babel import gettext as _
from flask_limiter.errors import RateLimitExceeded
from flask_login import login_required, current_user, logout_user, login_user
from flask_mail import Message
from learning_platform import bcrypt, db, app, mail, limiter
from learning_platform.forms.form import Registration, LoginForm, ResetForm, NewPasswordForm
from learning_platform.models.models import User, Course, SubTopic, User_solution
from learning_platform.google_translations import text_translator
from learning_platform._helpers import (
    c_and_topics, cached, validate_time_task, get_ref, get_lang, presigned_url,
    presigned_cert_url, upload_certificate, s3_client, encryption, verify_payment, completed_course)
from PIL import Image, ImageDraw, ImageFont

user_bp = Blueprint('users', __name__, static_folder='static',
                    template_folder='templates')


ref = []


def cert_available(key):
    s3 = s3_client()
    cert = f'{encryption("cert")[:16]}'
    try:
        s3.get_object(Bucket=cert, Key=key)
    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchKey':
            return False
    return True


def pop_ref():
    for i, v in enumerate(ref):
        ref.pop(i)


def user_enrolled_courses(course_id):
    if not current_user.is_authenticated:
        flash(_('please login first'), category='info')
        return redirect(url_for('home.home'))
    user_courses = current_user.enrolling
    for c in user_courses:
        if c.id == course_id:
            return True, c
    return False, None


def completed_topics(c):
    user = current_user
    all = 0
    some = 0
    for u in c.time_task.sub_topic:
        all += 1
        for t in user.user_solu.sub_topics:
            if u.name_a == t.name_a:
                some += 1
                break
    return int((some / all) * 100)


@user_bp.errorhandler(RateLimitExceeded)
def rateLimit_handler(e):
    return jsonify(error='something went wrong. try again')


@user_bp.route('/register', methods=['GET', 'POST'])
def register():
    l = 'This name will appear on your certificate when you enroll in a course'
    lang = get_lang()
    if lang != "en":
        l = text_translator(l, lang)

    form = Registration(request.form)
    if form.validate_on_submit():
        fullname = form.fullname.data
        username = form.username.data
        email = form.email.data
        moderator = False
        hashed_password = bcrypt.generate_password_hash(form.password.data)

        if not User.query.filter_by(email=email).first():
            user = User(fullname=fullname, username=username, email=email,
                        password=hashed_password, moderator=moderator)

            user.user_solu = User_solution(user=user)
            db.session.add(user)
            db.session.commit()
            if moderator:
                flash(
                    f"you have successfully registered {fullname} as admin",
                    category='success')
            else:
                flash(_("Thank you for Registering"), category='success')
        return redirect(url_for('users.login'))
    return render_template('user/register.html', form=form, l=l)


@user_bp.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        try:
            if user and bcrypt.check_password_hash(
                    user.password, form.password.data):
                user.authenticated = True
                db.session.add(user)
                db.session.commit()
                login_user(user)
                next = request.args.get(
                    'next_url') or url_for('users.userprofile')
                flash(_('Happy Coding!  😊'), category='success')
                return redirect(next)
            flash(_("Invalid Credentials"), category='warning')
            return redirect(url_for('users.login'))
        except BaseException:
            return redirect(url_for('users.login'))

    return render_template('user/login.html', form=form)


@user_bp.route("/logout", methods=['GET', 'POST'])
@login_required
def user_logout():
    '''the user will log out from here
    '''
    if not current_user.is_authenticated:
        return redirect(url_for('home.home'))
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    return redirect(url_for('home.home'))


@user_bp.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    form = ResetForm()
    if form.validate_on_submit():
        email = form.email.data
        user = User.query.filter_by(email=email).first()

        lnk_ms = 'Click this link to reset your password'
        if get_lang() != 'en':
            lnk_ms = text_translator(lnk_ms, get_lang())

        if user:
            token = get_ref()
            user.reset_token = token
            db.session.commit()
            msg = Message(_('Password Reset Request'),
                          sender='skildemycontact@gmail.com',
                          recipients=[email])
            msg.body = f'''
            {lnk_ms}
            {url_for('users.reset_password', token=token, _external=True)}
            '''
            mail.send(msg)

            flash(_('Check your email for the password reset link.'),
                  category='success')
        else:
            flash(_('Email not found'), category='danger')
            return redirect(url_for('users.login'))
    return render_template(
        'user/reset_password.html',
        form=form,
        title='Reset Password')


@user_bp.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    form = NewPasswordForm()
    user = User.query.filter_by(reset_token=token).first()
    if user:
        if request.method == 'POST':
            new_password = request.form['password']
            user.set_password(new_password)
            user.reset_token = None
            db.session.commit()
            flash(_('successfully reset password'))
            return redirect(url_for('users.login'))
    return render_template('user/reset_password_confirm.html', form=form)


@user_bp.route('/enrol/<string:course_id>', methods=['GET', 'POST'])
@login_required
def enroll_course(course_id):
    '''the student will enroll in the course
    '''
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))
    status, result = verify_payment(ref[0])

    if status:
        course = Course.query.get(course_id)

        price = course.price
        rate = course.rate
        if result['amount'] > rate * price * 65:

            mes = _('You have successfully enrolled in', category='success')
            for c in current_user.enrolling:
                if c == course:
                    c.update_enrolled_at(datetime.now())
                    mes = _('You have successfully updated your course')
                    break
            else:
                course.update_enrolled_at(datetime.now())
                current_user.enrolling.append(course)
            db.session.commit()

            flash(
                f'{mes} {course.name}', category='info')
            return render_template('payment/success.html')
    else:
        flash(
            _('unsuccessful, please check your details or contact SKILdemy support'),
            category='info')
        return render_template('payment/unsuccessful.html')


@user_bp.route("/userprofile", methods=['GET', 'POST'])
def userprofile():
    '''this will initiate the user profile setting
    '''
    if not current_user.is_authenticated:
        next_url = request.url
        return redirect(url_for('users.login', next_url=next_url))
    

    _lis = []
    user_courses = current_user.enrolling
    for c in user_courses:
        st, v = completed_course(c)
        pct = completed_topics(c)

        if v >= 0:
            ms = text_translator(str(v) + ' days left', get_lang())
            _lis.append([c, ms, pct])
        else:
            _lis.append([c, ' ', pct])

    return render_template('user/profile.html',
            user_courses=_lis)


@user_bp.route('/next_page/<int:page>/<int:fp>/<int:lp>',
               methods=['GET', 'POST'])
def paginate(page, fp, lp):
    '''the topics will be paginated here
    '''
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))

    fk = session.get('c')
    fv = session.get('dict')

    return render_template(
        'user/learn_page.html',
        fk=fk,
        fv=fv,
        page=str(page),
        fp=fp,
        lp=lp)


@user_bp.route('/learns/<string:course_id>', methods=['GET', 'POST'])
def learn_skills(course_id):
    '''the course and topics will be displayed for the
    '''
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))

    status, course = user_enrolled_courses(course_id)
    if not status:
        return redirect(url_for('users.login'))
    
    compl_c, n_ = completed_course(course)
    if compl_c:
                flash(
                    _('Please your time period to access this course has elapsed'),
                    category='warning')
                flash(
                    _('You can always extend the time without losing your current records'),
                    category='info')
                return redirect(url_for('users.userprofile'))
   
    c_and_t = c_and_topics(course)
    first_key, first_value = next(iter(c_and_t.items()))
    dict_val = {}
    for i, j in enumerate(first_value):
        dict_val[str(i)] = j

    session['dict'] = dict_val
    session['c'] = first_key
    page = '0'

learning_platform/templates/home/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    
    <title>
        {% block title %}SKILdemy{% endblock %}
    </title>
</head>
<body>
    {% block main %}
    <div class="container-fluid">
       <div class="row nav">
        <nav>
            {% if auth %}
            <div>
                <a class="btn btn-info fs-4 m-2" href="{{ url_for('users.userprofile')}}">
                    {{ _('Dashboard') }}
                </a>
            </div>
            <div>
                <a class="" href="{{ url_for('users.user_locale')}}"> 
                    <img src="{{ url_for('static', filename='flags/' + lang)}}" alt="">   
                </a>
            </div>
            {% else %}
            <div >
                <div class="" id="register">
                    <a class="btn btn-info fs-3" href="{{ url_for('users.register') }} " id="auth">
                        {{ _('Register') }}
                    </a>
                </div>
            </div>
            <div >
                <div class="" id="sign-in">
                    <a class="btn btn-info fs-3" href="{{ url_for('users.login') }}" id="auth">
                        {{ _('login') }}
                    </a>
                </div>
              </div>
            {% endif %}
            </nav>
    
       </div>
       <p class="text-light">{{ welc }}</p>
       <div class="row ">
        {% if topics %} 
        
        <div class="col" style="background-color: rgb(240, 240, 241);">           
            <nav aria-label="...">
                <ul class="pagination">
                  <li class="page-item active">
                    <a class="page-link" href="{{ url_for('home.home') }}">{{_('Back')}}</a>
                  </li>
                </ul>
              </nav>
              <div class="fs-2 text-center text-info"> {{ course.name }}</div>
              
                <p style="background-color: black; max-width: fit-content; color: white;"
                class="text-center fs-3">{{desc}}</p>
            <p>
              
              
                <ul>   
                        <h3 class="text-info">{{_('course content')}}</h3>
                        {% for topic in topics|sort(attribute='created_at') %}
                         <li class="fs-3 text-success">
                            {{ topic.name  }}
                            <ol style="background-color: rgb(248, 251, 252);" class="fs-5">
                                {% for subt in topic.sub_topics%}
                                <li class="text-dark">
                                    {% if subt.name in tr %}
                                    <p style="font-size: larger;" class="text-info">
                                        <a style="text-decoration: none; font-size: xx-large;" class="fs-2 btn btn-info"
                                        href="{{ url_for('users.free_test', course_id=course.id, topic_id=subt.id) }}">
                                        <span class="btn btn-outline-success"> {{subt.name}} </span> <span> {{_('Try this for free')}}</span>
                                        </a>   
				    </p>
				    {% else %}
                                    <p style="font-size: larger;" class="text-secondary">
                                        {{subt.name}}
                                    </p>
                                    {% endif %}
                                </li>

                                {% endfor %}

                            </ol>
                        </li>
                        {% endfor %}
                </ul>
    
            </p>
        </div>
        
        {% else %}
        <h2 style="text-align: center; color: #83e4cf;">
            {{_('click on course for more information')}}
        </h2>
      <div class="parent"> 
        
    {% for course in courses %}        
    <div class="text-light" id="course">
        <div class="d-flex justify-content-end bg-dark">
            <a class="btn btn-info m-2" id="enrol" 
            href="{{ url_for('users.make_payment', course_id=course.id) }}" >
                {{ _('Enroll now') }}
            </a>
        </div>
        <a class="text-dark"  style="text-decoration: none;" 
        href="{{ url_for('home.home_', course_id=course.id) }}">
        <div class="col">
            <div class="pb-4 btn btn-outline-success fs-2">{{ course.name }}</div>
            <div>
                <p class="text-center text-success fs-5 text-secondary">
                    </p>
            </div>
            <div style=" color: red; margin-bottom: 24px;" class="text-center">
                <span style="min-width: auto; background-color: rgb(12, 14, 4); font-size: medium;">
                    
                </span>
                </div>
            <div class="fs-3 text-center text-dark"> $ <span class="fs-3 text-success">{{ course.price }}
            </span></div>            
        </div>
    </a>
    </div>
    {% endfor %}
</div>
    {% endif %}
       </div>
      </div>
    {% endblock %}   
</body>
</html>