learning_platform/views/users.py
import os
import io
from datetime import datetime, timedelta
import requests
from flask import (
    Blueprint, render_template, redirect, url_for, request, jsonify, flash, session, send_file)
from botocore.exceptions import ClientError
from flask_babel import gettext as _
from flask_limiter.errors import RateLimitExceeded
from flask_login import login_required, current_user, logout_user, login_user
from flask_mail import Message
from learning_platform import bcrypt, db, app, mail, limiter
from learning_platform.forms.form import Registration, LoginForm, ResetForm, NewPasswordForm
from learning_platform.models.models import User, Course, SubTopic, User_solution
from learning_platform.google_translations import text_translator
from learning_platform._helpers import (
    c_and_topics, cached, validate_time_task, get_ref, get_lang, presigned_url,
    presigned_cert_url, upload_certificate, s3_client, encryption, verify_payment, completed_course)
from PIL import Image, ImageDraw, ImageFont

user_bp = Blueprint('users', __name__, static_folder='static',
                    template_folder='templates')


ref = []


def cert_available(key):
    s3 = s3_client()
    cert = f'{encryption("cert")[:16]}'
    try:
        s3.get_object(Bucket=cert, Key=key)
    except ClientError as e:
        if e.response['Error']['Code'] == 'NoSuchKey':
            return False
    return True


def pop_ref():
    for i, v in enumerate(ref):
        ref.pop(i)


def user_enrolled_courses(course_id):
    if not current_user.is_authenticated:
        flash(_('please login first'), category='info')
        return redirect(url_for('home.home'))
    user_courses = current_user.enrolling
    for c in user_courses:
        if c.id == course_id:
            return True, c
    return False, None


def completed_topics(c):
    user = current_user
    all = 0
    some = 0
    for u in c.time_task.sub_topic:
        all += 1
        for t in user.user_solu.sub_topics:
            if u.name_a == t.name_a:
                some += 1
                break
    return int((some / all) * 100)


@user_bp.errorhandler(RateLimitExceeded)
def rateLimit_handler(e):
    return jsonify(error='something went wrong. try again')


@user_bp.route('/register', methods=['GET', 'POST'])
def register():
    l = 'This name will appear on your certificate when you enroll in a course'
    lang = get_lang()
    if lang != "en":
        l = text_translator(l, lang)

    form = Registration(request.form)
    if form.validate_on_submit():
        fullname = form.fullname.data
        username = form.username.data
        email = form.email.data
        moderator = False
        hashed_password = bcrypt.generate_password_hash(form.password.data)

        if not User.query.filter_by(email=email).first():
            user = User(fullname=fullname, username=username, email=email,
                        password=hashed_password, moderator=moderator)

            user.user_solu = User_solution(user=user)
            db.session.add(user)
            db.session.commit()
            if moderator:
                flash(
                    f"you have successfully registered {fullname} as admin",
                    category='success')
            else:
                flash(_("Thank you for Registering"), category='success')
        return redirect(url_for('users.login'))
    return render_template('user/register.html', form=form, l=l)


@user_bp.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        try:
            if user and bcrypt.check_password_hash(
                    user.password, form.password.data):
                user.authenticated = True
                db.session.add(user)
                db.session.commit()
                login_user(user)
                next = request.args.get(
                    'next_url') or url_for('users.userprofile')
                flash(_('Happy Coding!  😊'), category='success')
                return redirect(next)
            flash(_("Invalid Credentials"), category='warning')
            return redirect(url_for('users.login'))
        except BaseException:
            return redirect(url_for('users.login'))

    return render_template('user/login.html', form=form)


@user_bp.route("/logout", methods=['GET', 'POST'])
@login_required
def user_logout():
    '''the user will log out from here
    '''
    if not current_user.is_authenticated:
        return redirect(url_for('home.home'))
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    return redirect(url_for('home.home'))


@user_bp.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    form = ResetForm()
    if form.validate_on_submit():
        email = form.email.data
        user = User.query.filter_by(email=email).first()

        lnk_ms = 'Click this link to reset your password'
        if get_lang() != 'en':
            lnk_ms = text_translator(lnk_ms, get_lang())

        if user:
            token = get_ref()
            user.reset_token = token
            db.session.commit()
            msg = Message(_('Password Reset Request'),
                          sender='skildemycontact@gmail.com',
                          recipients=[email])
            msg.body = f'''
            {lnk_ms}
            {url_for('users.reset_password', token=token, _external=True)}
            '''
            mail.send(msg)

            flash(_('Check your email for the password reset link.'),
                  category='success')
        else:
            flash(_('Email not found'), category='danger')
            return redirect(url_for('users.login'))
    return render_template(
        'user/reset_password.html',
        form=form,
        title='Reset Password')


@user_bp.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    form = NewPasswordForm()
    user = User.query.filter_by(reset_token=token).first()
    if user:
        if request.method == 'POST':
            new_password = request.form['password']
            user.set_password(new_password)
            user.reset_token = None
            db.session.commit()
            flash(_('successfully reset password'))
            return redirect(url_for('users.login'))
    return render_template('user/reset_password_confirm.html', form=form)


@user_bp.route('/enrol/<string:course_id>', methods=['GET', 'POST'])
@login_required
def enroll_course(course_id):
    '''the student will enroll in the course
    '''
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))
    status, result = verify_payment(ref[0])

    if status:
        course = Course.query.get(course_id)

        price = course.price
        rate = course.rate
        if result['amount'] > rate * price * 65:

            mes = _('You have successfully enrolled in', category='success')
            for c in current_user.enrolling:
                if c == course:
                    c.update_enrolled_at(datetime.now())
                    mes = _('You have successfully updated your course')
                    break
            else:
                course.update_enrolled_at(datetime.now())
                current_user.enrolling.append(course)
            db.session.commit()

            flash(
                f'{mes} {course.name}', category='info')
            return render_template('payment/success.html')
    else:
        flash(
            _('unsuccessful, please check your details or contact SKILdemy support'),
            category='info')
        return render_template('payment/unsuccessful.html')


@user_bp.route("/userprofile", methods=['GET', 'POST'])
def userprofile():
    '''this will initiate the user profile setting
    '''
    if not current_user.is_authenticated:
        next_url = request.url
        return redirect(url_for('users.login', next_url=next_url))
    

    _lis = []
    user_courses = current_user.enrolling
    for c in user_courses:
        st, v = completed_course(c)
        pct = completed_topics(c)

        if v >= 0:
            ms = text_translator(str(v) + ' days left', get_lang())
            _lis.append([c, ms, pct])
        else:
            _lis.append([c, ' ', pct])

    return render_template('user/profile.html',
            user_courses=_lis)


@user_bp.route('/next_page/<int:page>/<int:fp>/<int:lp>',
               methods=['GET', 'POST'])
def paginate(page, fp, lp):
    '''the topics will be paginated here
    '''
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))

    fk = session.get('c')
    fv = session.get('dict')

    return render_template(
        'user/learn_page.html',
        fk=fk,
        fv=fv,
        page=str(page),
        fp=fp,
        lp=lp)


@user_bp.route('/learns/<string:course_id>', methods=['GET', 'POST'])
def learn_skills(course_id):
    '''the course and topics will be displayed for the
    '''
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))

    status, course = user_enrolled_courses(course_id)
    if not status:
        return redirect(url_for('users.login'))
    
    compl_c, n_ = completed_course(course)
    if compl_c:
                flash(
                    _('Please your time period to access this course has elapsed'),
                    category='warning')
                flash(
                    _('You can always extend the time without losing your current records'),
                    category='info')
                return redirect(url_for('users.userprofile'))
   
    c_and_t = c_and_topics(course)
    first_key, first_value = next(iter(c_and_t.items()))
    dict_val = {}
    for i, j in enumerate(first_value):
        dict_val[str(i)] = j

    session['dict'] = dict_val
    session['c'] = first_key
    page = '0'

learning_platform/templates/user/certificate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>{{_('certificate')}}</title>
</head>
<body>
    {% block main %}
    <h1 class="fs-2 m-3" style="background-color: rgb(34, 22, 22); color: whitesmoke; text-align: center;">
        {{_('congratulations')}} 🎉🎉🎉  🥇</h1>
    <p class="text-center" style="margin: 24px;">
        <a href="{{url_for('users.download_cert', course_id=course_id)}}" style="text-decoration: none;
         font-size: x-large; background-color: white; ">
            {{_('proceed for certificate')}}
        </a>
    </p>
    {% endblock %}
</body>
</html>

learning_platform/templates/user/free_trial.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% extends "base.html" %}
    <title>{% block title %} learn {% endblock %}</title>
</head>
<body>
  {% block main %}
  <nav><a class="btn btn-primary" href="{{url_for('home.home')}}">{{_('Home')}}</a></nav>
        <div class="container-fluid">
            <div class="row">
                {% if fk %}                   
                <div class="col" style="display: flex; flex-direction: column;">
                  <div>
                    <p class=""><h1 class="btn btn-secondary fs-2 ">{{fk}}</h1></p>
                    <p class="m-3">
                      <a style="text-decoration: none; font-size: xx-large;" class="fs-2 btn btn-info"
                      href="{{ url_for('users.topic_by_course', course_id=fv[page][1], topic_id=fv[page][2]) }}">
                        {{ fv[page][0] }}
                      </a>
                    </p>               
                  </div>                              
                </div>
                {% elif mat %}
                <div class="col fs-3" style="background-color: rgb(214, 255, 159);">
                    <a class="btn btn-primary m-3" href="{{ url_for('home.home', course_id=course_id) }}">{{_('Back')}}</a>
                    <div class="row">
                       <nav id="ai-yt">
                        <div class="col text-success">
                          <a class="btn btn-primary" 
                          href="{{ url_for('users.gptplus_vid', course_id=course_id, topic_id=topic_id) }}">
                          {{_('SKILdemy guide')}}
                          <img src="{{ url_for('static', filename='thumbnail/thumbnail.png') }}" alt="thumbnail">
                        </a>
                        </div>
                        <div class="btn-group">
                          <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                            {{_('Suggested Videos')}}
                            <img src="{{ url_for('static', filename='thumbnail/youtube.png') }}" alt="thumbnail">
                          </button>
                          <ul class="dropdown-menu" style="background-color: rgb(58, 37, 37);">
                          
                            {% for idx in path %}
			                      <p class="fs-3 text-info text-center"
                             style="background-color: rgb(43, 43, 61);">SKILdemy</p>
                            <li>
                              
                                <iframe width="560" height="315" 
                                src="https://www.youtube.com/embed/{{ idx }}"
                                title="YouTube video player" 
                                frameborder="0" 
                                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
                                referrerpolicy="strict-origin-when-cross-origin" allowfullscreen>
                                </iframe>
                              
                            </li>
                            {% endfor %}

                          </ul>
                        </div>
                        
                        
                       </nav>  
                    <div>
                {% for line in mat.split('\n') %}

                {% if line.startswith('http') %}
                  <a href="{{line}}">
                    {{line}}
                  </a>
                {% else %}
                  {{ line }}

                {% endif %}
               <br>
               {% endfor %}
                </div>
                    </div>
                </div>
                {% elif path and not_time %}
                <div class="col-md-4">
                  <video width="640" controls>
                    <source src="{{ path }}" type="video/mp4">
                  </video>
                </div>

                {% elif path and pending %}
                <div class="col-md-4">
                  <video controls class="col-md-12">
                    <source src="" type="video/mp4">
                  </video>
                  <div class="text-end ">
                    <a class="btn btn-danger text-info fs-3" href="">
                      {{_('Cancel Request')}}
                    </a>
                  </div>
                </div>

                {% elif path and ask %}
                <p class="fs-3 text-light">
                  {{_('keep learning while we prepare the answers for you')}}
                </p>
                <div class="col-md-4">
                  
                  <video controls  class="col-md-12">
                    <source src="" type="video/mp4">
                  </video>
                  <div class="text-end ">
                    <a class="btn btn-success text-info fs-3" href="{{ url_for('users.request_task_solution', topic_id=topic_id) }}">
                      
                      {{_('Request Solution')}}
                    </a>
                  </div>
                </div>
                {% endif %}
            </div>
        </div>
  
{% endblock %}
</body>
</html>

learning_platform/templates/user/learn_page.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% extends "base.html" %}
    <title>{% block title %} learn {% endblock %}</title>
</head>
<body>
  {% block main %}
  <nav><a class="btn btn-primary" href="{{url_for('users.userprofile')}}">{{_('Home')}}</a></nav>
        <div class="container-fluid">
            <div class="row" style="background-color: black; justify-content: center;">
                {% if fk %}
                <p class="text-info text-center fs-2 btn btn-light">
                    {{_('PROGRESS')}}: <span class="text-success" style="font-weight: bolder; height: 120px; width: 120px;
                     border-radius: 60px; background-color: black; padding: 3px;">
                    {{ (((page | int +1) / (lp|int + 1))*100) | int }}</span>
                </p>
                        
                <div class="col" style="display: flex; flex-direction: column;">
                  <div>
                    <p class=""><h1 class="btn btn-secondary fs-2 ">{{fk}}</h1></p>

                    <p class="m-3">
                      <a style="text-decoration: none; font-size: xx-large;" class="fs-2 btn btn-info"
                      href="{{ url_for('users.topic_by_course', course_id=fv[page][1], topic_id=fv[page][2]) }}">
                        {{ fv[page][0] }}
                      </a>
                    </p>
                   
                  </div>
                    <div style="display: flex; flex-direction: row; justify-content: space-between;">
                      {% if page | int > fp   %}
                   <p> <a href="{{ url_for('users.paginate', page= (page | int - 1), fp=fp, lp=lp) }}">
                    {{_('PREVIOUS')}}
                  </a></p>
                   {% endif %}

                   {% if lp > page | int %}
                   <p><a href="{{ url_for('users.paginate', page=(page | int + 1), fp=fp, lp=lp) }}">
                    {{_('NEXT')}}
                  </a></p>
                   {% endif %}
                    </div>                               
                </div>
                {% elif mat %}
                <div class="col fs-3" style="background-color: rgb(214, 255, 159);">
                    <a class="btn btn-primary" href="{{ url_for('users.learn_skills', course_id=course_id) }}">{{_('Back')}}</a>
                    <div class="row text-center">
                      
                       <nav id="sk">
                        <div class="col text-success text-center sk" style="margin-bottom: 1rem;">
                          <a href="{{ url_for('users.gptplus_vid', course_id=course_id, topic_id=topic_id) }}">
                            <p id="p">{{ _('SKILdemy guide') }}</p>
                              <img src="{{ url_for('static', filename='thumbnail/thumbnail.png') }}" alt="thumbnail"> 
                          </a>
                      </div>
                        <div class="col text-center sk" style="margin: 1rem;">
                          <div class="dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                            <p id="p">{{_('Suggested Videos')}}</p>
                            <img src="{{ url_for('static', filename='thumbnail/youtube.png') }}" alt="thumbnail">
                          </div>
                          <ul class="dropdown-menu" style="background-color: rgb(58, 37, 37);">
                          
                            {% for idx in path %}
			                      <p class="fs-3 text-info text-center" style="background-color: rgb(43, 43, 61);">SKILdemy</p>
                            <li>                             
                                <iframe width="560" height="315" 
                                src="https://www.youtube.com/embed/{{ idx }}"
                                title="YouTube video player" 
                                frameborder="0" 
                                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
                                referrerpolicy="strict-origin-when-cross-origin" allowfullscreen>
                                </iframe>                             
                            </li>
                            {% endfor %}
                          </ul>
                        </div>                      
                       </nav>  
                    <div class="txtdsp">
                {% for line in mat.split('\n') %}
                {% if line.startswith('http') %}
                  <a href="{{line}}">
                    {{line}}
                  </a>
                {% else %}
                  {{ line }}
                {% endif %}
               <br>
               {% endfor %}
                </div>
                    </div>
                </div>
                {% elif path and not_time %}
                <div style=" background-color: red;" class="text-center vidp">
                  <video controls >
                    <source src="{{ path }}" type="video/mp4">
                  </video>
                </div>
                {% elif path and pending %}
                <div style="max-width: fit-content;" class="text-center">
                  <video controls style="min-width: fit-content;">
                    <source src="" type="video/mp4">
                  </video>
                  <div class="text-end ">
                    <a class="btn btn-danger text-info fs-3" href="">
                      {{_('Cancel Request')}}
                    </a>
                  </div>
                </div>
                {% elif path and ask %}
                <p class="fs-3 text-light">
                  {{_('keep learning while we prepare the answers for you')}}
                </p>
                <div class="col-md-4">                 
                  <img src="{{ url_for('static', filename='thumbnail/ai.png') }}" alt="thumbnail" height="280" width="autp">
                  <div class="text-end ">
                    <a class="btn btn-success text-info fs-3" 
                    href="{{ url_for('users.request_task_solution', topic_id=topic_id) }}">
                      {{_('Request Solution')}}
                    </a>
                  </div>
                </div>
                {% endif %}
            </div>
        </div> 
{% endblock %}
</body>
</html>

learning_platform/templates/user/locale.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>
      {% block title %} dialet {% endblock %}
    </title>
    
</head>
    
<body>
  {% block main %}
  <div class="row align-items-start btn btn-outline-primary fs-5">
                    
    <form action="" method="post">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <label for="language">{{_('Choose a language:')}}</label>
        <select id="language" name="language">
          <option value="" disabled selected>{{_('select Language')}}</option>
          <option value="ar">{{_('Arabic')}}</option>
          <option value="bn">{{_('Bengali')}}</option>
          <option value="en">{{_('English')}}</option>
          <option value="fr">{{_('French')}}</option>
          <option value="de">{{_('German')}}</option>
          <option value="hi">{{_('Hindi')}}</option>
          <option value="id">{{_('Indonesian')}}</option>
          <option value="ja">{{_('Japanese')}}</option>
          <option value="ko">{{_('Korean')}}</option> 
          <option value="pt">{{_('Portuguese')}}</option>
          <option value="ru">{{_('Russia')}}</option>
          <option value="es">{{_('Spanish')}}</option>
          <option value="tr">{{_('Turkish')}}</option>
          <option value="ur">{{_('Urdu')}}</option>                   
        </select>
        <input type="submit" value="Select">
      </form>
</div>

    
    {% endblock %}
</body>

</html>

learning_platform/templates/user/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>{% block title %} login {% endblock %}</title>
</head>
    
<body>
  
  {% block main %}
  <nav class="text-info fs-1 text-center mt-5">{{_('login')}}</nav>
  
  <div class="container-fluid">
    <div class="row align-items-start">
      <div class="col-2"></div>
      <div class="col-8">
        {% from "_formhelpers.html" import render_field %}
<form method="post">
  {{ form.csrf_token }}
  <div class="bg-dark-subtle p-4 mt-3 text-primary fs-3"> 
    {{ render_field(form.email, class="form-control fs-4", placeholder="email@example.com") }}
    {{ render_field(form.password, class="form-control fs-4", placeholder="******") }}
  </div>
  <p class="text-center m-3"><input type=submit value="{{_('Login')}}" class="btn btn-primary btn-lg"></p>
  
  <div class="text-center">
    <a href="{{ url_for('users.forgot_password')}}" style="text-decoration-line: none;">
      {{_('Forgot Password')}}
    </a>
  </div>
</form>
      </div>
      <div class="col-2"></div>
      
    </div>
  </div>
{% endblock %}
</body>

</html>

learning_platform/templates/user/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>
      {% block title %} Dashboard {% endblock %}
    </title>
    
</head>
    
<body>
  {% block main %}
  <div class="container-fluid">

    <nav class="text-info fs-3" id="profile">
      <div class="child">
        <a class="" href="{{ url_for( 'home.home') }}">
          {{_('Home')}}
        </a>
      </div>
      
      <div class="child">
        <a class="" href="{{ url_for( 'users.user_logout') }}">
          {{_('logout')}}
        </a>
      </div>
      
    </nav>
    <div class="row">
        <div class="col bg-secondary" >
          <p>{{_('You will need at least 70 to pass this course for a certificate')}}</p>
            <p class="text-light fs-2">
              {{_('My courses')}}
            </p>
            {% for c in user_courses %}
            <div class="profile-info m-2 "> 
              <div class="btn btn-info" style="text-align: left;">
                <a href="{{ url_for('users.learn_skills', course_id=c[0].id) }}">
                   {{ c[0].name }} 
                </a>
                
                <span class=" text-danger">
                  {% if c[1] != ' ' %} {{ c[1]}}  {% endif %}
                </span>
              </div>
              <div style="background-color: bisque;">
                <a href="{{ url_for('users.cert_of_completion', course_id=c[0].id) }}">
                   {{_('Get certificate')}} <span style="font-size: 26px;">🎓</span>
                </a>
                <span class=" text-success">
                  <p>{{_('current score:')}} <span> {{ c[-1]}}</span></p>
                </span>
              </div>
              
            </div>
            {% endfor %}
        </div>
    </div>
  </div>
    {% endblock %}
</body>

</html>

learning_platform/templates/user/register.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% extends "base.html" %}
  <title>{% block title %} Register {% endblock %}</title>
</head>
<body>
  
  {% block main %}
  <div class="container-fluid">
  <nav class="text-info fs-3 text-center">{{_('Sign up')}}</nav>
  
    <div class="row align-items-start">
      <div class="col-2"></div>
      <div class="col-8">
  
  {% from "_formhelpers.html" import render_field %}
  <form action="/register" method="post">
    {{ form.csrf_token }}
    <div class="bg-dark-subtle text-primary fs-4"> 
      {{ render_field(form.fullname, class="form-control", placeholder=l) }}
      {{ render_field(form.username, class="form-control") }}
      {{ render_field(form.email, class="form-control", 
                      placeholder="*****1?*_@example.com" ) }}
      {{ render_field(form.password, class="form-control", 
                      placeholder="*****") }}
      {{ render_field(form.confirm, class="form-control", 
                      placeholder="*****") }}
    </div>
    <input type="submit" value="{{ _('Register') }}" class="btn btn-lg btn-primary">
  </form>
</div>
  <div class="col-2"></div>
</div>
</div>
  {% endblock %}
</body>
</html>

learning_platform/templates/user/reset_password.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>{% block title %} Enter Email {% endblock %}</title>
</head>
    
<body>
  {% block main %}
  <div class="container text-center">
    <div class="row align-items-start">
      <div class="col">
        {% from "_formhelpers.html" import render_field %}
<form method="post">
  {{ form.csrf_token }}
  <div class="bg-dark-subtle p-4 mt-5"> 
    {{ render_field(form.email, class="form-control fs-4", placeholder="email@example.com") }}
  </div>
  <input type=submit value="{{_('submit email')}}" class="btn btn-primary btn-lg mt-1">
</form>
      </div>
      
    </div>
  </div>


{% endblock %}
</body>

</html>

learning_platform/templates/user/reset_password_confirm.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>{% block title %} login {% endblock %}</title>
</head>   
<body>
  {% block main %}
  <div class="container text-center">
    <div class="row align-items-start">
      <div class="col">
        {% from "_formhelpers.html" import render_field %}
<form method="post">
  {{ form.csrf_token }}
  <div class="bg-dark-subtle p-4 mt-5"> 
    {{ render_field(form.password, class="form-control fs-4", placeholder="password...") }}   
  </div>
  <input type=submit value='submit password' class="btn btn-primary btn-lg mt-1"> 
</form>
      </div> 
    </div>
  </div>
{% endblock %}
</body>
</html>

learning_platform/templates/user/view_cert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>
      {% block title %} Dashboard {% endblock %}
    </title>
</head>
<body>
    {% block main %}
    <div class="text-center size">
        <img src="{{ dest }}"
         alt=""
         height="540">
         <button>
            <a href="{{ url_for('users.download_your_cert', id=id)}}" class="fs-2 btn btn-info">
                {{_('download')}}
            </a>
        </button>
    </div>
    {% endblock %}
</body>
</html>