learning_platform/views/admin.py
import os
from bson import ObjectId
from flask import (Blueprint, render_template, redirect, url_for, request, 
                   flash, session, jsonify)
from flask_babel import gettext as _
from flask_login import login_required, current_user
from learning_platform import bcrypt, db
from learning_platform.forms.form import (
    Registration, CourseForm, TopicForm, SubTopicForm)
from learning_platform.models.models import (
    User, Course, SubTopic, Topic, TimeTask)
from functools import wraps
from learning_platform._helpers import (
    upload_s3vid_languages, encryption, acceptable, insert_text, course_topic, c_and_topics, tream,
    file_, delete_byID, exchange_rate, unlink_file,update_ai_text, update_by_id, update_trans_by_id,
    live_text_Display_AI_content, user_courses, get_text_desc, recieve_displayed_text, get_byID, text_data,
    update_display_text, live_display_text_content, get_display_text_byID, delete_display_text_byID
    )


admin_bp = Blueprint(
    'admin', __name__, static_folder='static', template_folder='templates')


def validate_subtopic_for_topic(topic_id, subtopic_id):
    '''this ensures there is no topic with the same name
    '''

    topics = Topic.query.get(topic_id)
    for t in topics.sub_topics:
        if t.id == subtopic_id:
            return False
    return True


def validate_topic_for_course(course_id, topic_id):
    '''this ensures there is no topic with the same name
    '''

    course = Course.query.get(course_id)
    for t in course.topics:
        print(f'{type(t.id)} and {type(topic_id)}')
        if t.id == topic_id:
            return False
    return True


def validate_subject(course_id, subject_id):
    '''this ensures there is no subject with the same name
    '''
    course = Course.query.get(course_id)
    for s in course.subjects:
        if s.id == subject_id:
            return False
    return True


def admin_required(f):
    @wraps(f)
    def dec_func(*args, **kwargs):
        '''this will authenticated a user
        '''
        if not current_user.is_authenticated or current_user.moderator != True:
            flash('Only admins allowed here', category='danger')
            return redirect(url_for('users.login'))
        return f(*args, **kwargs)
    return dec_func


@admin_bp.route('/reg_admin')
def reg_admin():
    '''the admin will be registered here
    '''
    username = os.getenv("ADMIN_USERNAME")
    fullname = os.getenv("ADMIN_FULLNAME")
    email = os.getenv("ADMIN_EMAIL")
    admin_password = os.getenv("ADMIN_PASSWORD")
    hashed = bcrypt.generate_password_hash(admin_password)
    moderator = True
    main_admin = User(fullname=fullname, username=username, email=email,
                      password=hashed, moderator=moderator)
    db.session.add(main_admin)
    db.session.commit()

    return "admin created successfully"


@admin_bp.route('/admin')
@admin_required
def admin():
    '''an admin route
    '''
    return render_template('admin/index.html')


@admin_bp.route('/create_user', methods=["GET"])
@login_required
@admin_required
def create_user():
    '''the creation of admin will start here
    '''
    form = Registration(request.form)
    return render_template('user/register.html', form=form)


@admin_bp.route('/upload/<string:language>/<string:course_id>/<string:topic_id>',
                methods=['GET', 'POST'])
def upload(language, course_id, topic_id):
    '''a file will be uploaded here
    '''
    # validate_list()
    if request.method == 'POST':
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        if file and acceptable(file.filename):
            course = Course.query.get(course_id)
            topic = SubTopic.query.get(topic_id)
            _name = f'{course.course_creator}{topic.topic_id}{topic.name}'

            name = encryption(_name) + '.mp4'

            upload_s3vid_languages(file, name, language)

            flash('successfully added the video', category='success')
        return redirect(url_for('admin.admin'))


@admin_bp.route('/reg_course', methods=['GET', 'POST'])
def register_course():
    '''this will add a course to the course table
    '''
    form = CourseForm(request.form)
    if form.validate_on_submit():
        name = form.name.data
        desc = form.description.data
        price = form.price.data
        duration = form.duration.data
        creator = current_user.username
        rate = exchange_rate()
        new_course = Course(
            name=name,
            course_creator=creator,
            description=desc,
            price=price,
            duration=duration,
            rate=rate)
        timely = TimeTask(course=new_course)
        db.session.add(new_course)
        db.session.add(timely)
        db.session.commit()
        return jsonify({'message': 'Course created successfully'}), 201
    return render_template(
        'content_management/register_course.html',
        form=form)


@admin_bp.route('/tim/')
@admin_bp.route('/tim/<string:c_id>')
def timely_topics(c_id):
    '''course to work with to be selected here
    '''
    if c_id != ' ':
        course = Course.query.get(c_id)
        c_and_t = c_and_topics(course)
        _, fv = next(iter(c_and_t.items()))
        return render_template('content_management/timely_asso.html', fv=fv)
    courses = Course.query.all()
    return render_template(
        'content_management/timely_course.html',
        courses=courses)


@admin_bp.route('/ctim/<string:stop_id>/<string:c_id>')
def course_timely_asso(stop_id, c_id):
    '''tasks will be added here
    '''
    course = Course.query.get(c_id)
    c_and_t = c_and_topics(course)
    _, fv = next(iter(c_and_t.items()))
    topic = SubTopic.query.get(stop_id)

    for sub_topic in course.time_task.sub_topic:
        if sub_topic.id == stop_id:
            flash('already associated', category='warning')
            break
    else:
        topic.update_name_a(encryption(f'{c_id}{stop_id}{topic.topic_id}'))
        course.time_task.sub_topic.append(topic)
        db.session.commit()
        flash('successfully added to delayed tasks', category='success')
    return render_template('content_management/timely_asso.html', fv=fv)


@admin_bp.route('/t/')
@admin_bp.route('/t/<string:c_id>')
def free_topics(c_id):
    '''the topics to be allowed for free
    '''
    if c_id != ' ':
        course = Course.query.get(c_id)
        c_and_t = c_and_topics(course)
        _, fv = next(iter(c_and_t.items()))
        return render_template(
            'content_management/course_free_topic.html', fv=fv)

    courses = Course.query.all()
    return render_template('content_management/courses.html', courses=courses)


@admin_bp.route('/cfass/<string:stop_id>/<string:c_id>')
def course_free_asso(stop_id, c_id):
    course = Course.query.get(c_id)
    trial = SubTopic.query.get(stop_id)

    c_and_t = c_and_topics(course)
    _, fv = next(iter(c_and_t.items()))

    if trial not in course.trial_topics:
        course.trial_topics.append(trial)
        flash('success', category='success')
        db.session.commit()
        return render_template(
            'content_management/course_free_topic.html', fv=fv)

    flash('already associated', category='warning')
    return render_template('content_management/course_free_topic.html', fv=fv)


@admin_bp.route('/cs_avail', methods=['GET', 'POST'])
def cs_avail():
    '''this will get all the available courses
    '''
    cst = Course.query.all()
    return render_template('content_management/delete_course.html', cst=cst)


@admin_bp.route('/add_topic', methods=['GET', 'POST'])
def add_topic():
    '''this will add a topic to the topic table
    '''
    form = TopicForm(request.form)
    if form.validate_on_submit():
        topic = form.name.data
        new_topic = Topic(name=topic)
        db.session.add(new_topic)
        db.session.commit()
        flash('added to the topics', category='info')
    return render_template('content_management/add_topic.html', form=form)


@admin_bp.route('/ts_avail', methods=['GET'])
def ts_avail():
    '''this will get all the available topics
    '''
    cst = Topic.query.all()
    return render_template('content_management/delete_topic.html', cst=cst)


@admin_bp.route('/add_subtopic', methods=['GET', 'POST'])
def add_sub_topic():
    '''this will add a topic to the topic table
    '''
    form = SubTopicForm(request.form)
    if form.validate_on_submit():
        subtopic = form.name.data
        new_subtopic = SubTopic(name=subtopic)
        db.session.add(new_subtopic)
        db.session.commit()
        flash(f'{subtopic} successfully added to the topics', category='info')
    return render_template('content_management/add_subtopic.html', form=form)


@admin_bp.route('/sts_avail', methods=['GET', 'POST'])
def sts_avail():
    '''
    ts_avail:
        this will get all the available sub topics
    '''
    cst = SubTopic.query.all()
    return render_template('content_management/delete_subtopic.html', cst=cst)


@admin_bp.route('/add_tc', methods=['GET', 'POST'])
def add_tc():
    '''this will add a particular topic to a particular course
    '''
    courses = Course.query.all()
    topics = Topic.query.all()
    if request.method == "POST":
        course_id = request.form.get('course_id')
        topic_id = request.form.get('topic_id')
        topic = Topic.query.get(topic_id)
        status = validate_topic_for_course(course_id, topic_id)
        if status:
            course = Course.query.get(course_id)
            course.topics.append(topic)
            db.session.commit()
            flash(f'added {topic} to {course}', category='success')
            return render_template(
                'content_management/topic_to_course.html',
                courses=courses,

learning_platform/templates/content_management/delete_course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>{% block title %}delete course{% endblock %}</title>
</head>
<body>
    {% block main %}
    {% for _item in cst|sort(attribute='name') %}
    <div style="
    background-color: rgb(220, 248, 195); 
    margin-bottom: 25; border: 10px solid rgb(63, 54, 54);">
<p class="fs-2 text-start" style="color: lightseagreen;
    font-family: 'Lucida Sans', 'Lucida Sans Regular', 
    'Lucida Grande', 'Lucida Sans Unicode', Geneva, 
    Verdana, sans-serif;">
    {{ _item.name }}
</p>
            <a class="btn btn-danger" href="{{ url_for('admin.del_course', c_id=_item.id)}}">
                delete
            </a>            
        </div>     
    {% endfor %}
    {% endblock %}
</body>
</html>

learning_platform/templates/content_management/delete_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>{% block title %}delete topic{% endblock %}</title>
</head>
<body>
    {% block main %}
    {% for _item in cst|sort(attribute='created_at') %}
        <div style="
                    background-color: rgb(220, 248, 195); 
                    margin-bottom: 25; border: 10px solid rgb(63, 54, 54);">
            <p class="fs-2 text-start" style="color: lightseagreen;
                    font-family: 'Lucida Sans', 'Lucida Sans Regular', 
                    'Lucida Grande', 'Lucida Sans Unicode', Geneva, 
                    Verdana, sans-serif;">
                {{ _item.name }}
            </p>
            <a class="btn btn-danger" href="{{ url_for('admin.del_topic', t_id=_item.id)}}">
                delete
            </a>            
        </div>     
    {% endfor %}
    {% endblock %}
</body>
</html>

learning_platform/templates/content_management/generate_ai_video.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% extends "base.html" %}
    <title>{% block title %} learn {% endblock %}</title>
</head>
<body>
  {% block main %}
  


        <div class="container-fluid">
          <div class="row align-items-center btn btn-outline-primary fs-5 m-4">
            <a href="{{ url_for('admin.get_published_AI')}}" class=" " id="admin">
                Preview Live AI Content
            </a>
        </div>
          <p  class=" btn btn-outline-success" style="display: block; font-size: large;" >
            Generate AI video
          </p>
            
              <div class="btn-group">
                
                <ul class="">
                    <div class="col" id="aid" >
                        {% for k, v in dict_v.items() %}
                        <p class="btn btn-secondary m-4 " style="display: block;">{{k}}</p>
                        {% for _t in v %}
                <li class="m-4" style="list-style: none;">
                  <a class="m-2 fs-2" 
                  href="{{ url_for('admin.gptplus', language=language,  course_id=_t[1], topic_id=_t[2]) }}">
                    Generate video for {{ _t[0] }}
                  </a>
                  <div style="background-color: antiquewhite;">
                    <form action="{{ url_for('admin.upload', language=language,  course_id=_t[1], topic_id=_t[2]) }}" method="post" enctype=multipart/form-data>
                      <input  type="hidden" name="csrf_token" value="{{ csrf_token() }}">       
                    <div class="col-4 fs-5 bg-info">
                      <label for="file">Select video</label><br>
                      <input type="file" id="file" name="file">
                    </div>               
                    <input type="submit" value="Upload video">
                  </form>
                  </div>              
                </li>
            {% endfor %}                 
            {% endfor %}
                    </div>
                </ul>            
              </div>           
        </div>     
{% endblock %}
</body>
</html>

learning_platform/templates/content_management/preview_ai_content.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>{% block title %} preview AI content {% endblock %}</title>
</head>
<body>
    {% block main %} 
        <div class="container">
            <div class="row">               
                <div class="col bg-dark">                  
                    {% for content in contents %}
                    {% if content[lang] %}
                    <a href="{{ url_for('admin.update_ai_translated_text', _id = content['_id'])}}" class="btn btn-info ">
                        Edit text
                    </a>
                    <p class="text-light fs-3">
                        {{ content[lang] }}
                    </p>                   
                    {% else %}
                    <p class="text-light">Nothing yet</p>
                    <div>
                        <a href="{{ url_for('admin.translate_ai_text', _id = content['_id'])}}">
                            Proceed to translate
                        </a>
                    </div>
                    {% endif %}
                    <div class="mb-5" style="background-color: #080808;">
                    <div class="btn btn-outline-success m-1">
                        {{content['course']}}
                    </div>
                    <br>
                    <div class="btn btn-outline-success m-1">{{content['topic']}}</div>
                    <br>                   
                    {% if content['code'] %}
                        <p class="text-light">{{ content['code'] }}</p>
                    <img src="{{ url_for('static', filename='default/code/' + content['code']) }}" alt="">
                    {% endif %}
                    {% if content['desc'] %}
                    <p class="text-light fs-3"> {{ content['desc'] }}</p>
                    {% endif %}
                    <div  class="" style="display: flex; flex-direction: row;
                                         justify-content: space-between;">
                        <a href="{{ url_for('admin.update_published_AI', _id = content['_id'])}}" class="btn btn-info ">
                            Edit
                        </a>
                        <a class="btn btn-danger" href="{{ url_for('admin.delete_ai_image', _id=content['_id'])}}">
                            Delete
                        </a>                     
                    </div>
                    </div>                   
                    {% endfor %}
                </div>            
            </div>
        </div>
    {% endblock %}
</body>
</html>

learning_platform/templates/content_management/preview_text_to_translate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>{% block title %} preview AI content {% endblock %}</title>
</head>
<body>
    {% block main %}
        <div class="container">
            <div class="row">          
                <div class="col bg-dark">
                    {% for content in contents %}
                    {% if content[lang] %}
                    <a href="{{ url_for('admin.edit_translation', _id = content['_id'])}}" class="btn btn-info ">
                        Edit text
                    </a>
                    <p class="text-light fs-3"> {{ content[lang] }}</p>                 
                    {% else %}
                    <p>Nothing yet</p>
                    {% endif %}
                    <div class="mb-5" style="background-color: #080808;">
                    <div class="btn btn-outline-success m-1">{{content['course']}}</div>
                    <br>
                    <div class="btn btn-outline-success m-1">{{content['topic']}}</div>
                    <br>
                    <a href="{{ url_for('admin.tream_original', _id = content['_id'])}}" class="btn btn-info ">
                        Edit text
                    </a>
                    {% if content['desc'] %}
                    <p class="text-light fs-3"> {{ content['desc'] }}</p>
                    {% endif %}
                     
                    <div  class="" style="display: flex; flex-direction: row;
                                         justify-content: space-between;">
                        <a href="{{ url_for('admin.update_text', _id = content['_id'])}}" class="btn btn-info ">
                            Proceed translation
                        </a>
                        <a class="btn btn-danger" href="{{ url_for('admin.delete_display_text', _id=content['_id'])}}">
                            Delete
                        </a>                        
                    </div>
                    </div>        
                    {% endfor %}
                </div>              
            </div>
        </div>
    {% endblock %}
</body>
</html>

learning_platform/templates/content_management/reading_text.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>{% block title %} Add course {% endblock %}</title>
</head>
<body>
    {% block main %}
    <div class="container">
        <div class="row">
            <form method="post" action="">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <div class="col">
                    <div class="dropdown">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Select Course
                        </a>

                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink1">
                            {% for c in courses %}
                            <li><a class="dropdown-item" href="#" onclick="setCourseId('{{ c.id }}')">{{ c.name }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="col mt-5 mb-5">
                    <div class="dropdown">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Select subject
                        </a>

                    </div>
                </div>
                <div class="col">
                    <div class="dropdown">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink2"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Select topic
                        </a>

                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink2">
                            {% for t in topics %}
                            <li><a class="dropdown-item" href="#" onclick="setTopicId('{{ t.id }}')">{{ t.name }}</a></li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
                <input type="hidden" name="course_id" id="course_id" value="">
                <input type="hidden" name="topic_id" id="topic_id" value="">
                <button type="submit" class="btn btn-primary mt-3">Submit</button>
            </form>
        </div>
    </div>
    <script>
        function setCourseId(id) {
            document.getElementById('course_id').value = id;
        }
        function setTopicId(id) {
            document.getElementById('topic_id').value = id;
        }
    </script>
    {% endblock %}
</body>
</html>

learning_platform/templates/content_management/register_course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>{% block title %} Create Course {% endblock %}</title>
</head>
<body>
    {% block body %}
    <div class="container text-center">
    <div class="row align-items-start">
        <div class="col-2"></div>
      <div class="col-8">
        {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="/reg_course">
        {{ form.hidden_tag() }}
        {{ form.csrf_token }}
        <div class="bg-dark-subtle p-4 mt-5"> 
        {{ render_field(form.name, class="form-control fs-4") }}
        {{ render_field(form.description, class="form-control fs-4") }}
        {{ render_field(form.price, class="form-control fs-4") }}
        {{ render_field(form.duration, class="form-control fs-4") }}
    </div>
        <div>
            <input type="submit" value="Create Course">
        </div>      
    </form>
</div>
<div class="col-2"></div>
</div>
</div>
{% endblock body %}
</body>
</html>

learning_platform/templates/content_management/timely_asso.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>{% block title %}Course{% endblock %}</title>
</head>
<body>
    {% block main %}
    {% for val in fv %}
    <a style="text-decoration: none; font-size: xx-large;" class="fs-3 btn btn-info m-2"
    href="{{ url_for('admin.course_timely_asso', stop_id=val[2], c_id=val[1]) }}">
      {{ val[0] }}
    </a> 
    <br>
    {% endfor %}
    {% endblock %}
</body>
</html>

learning_platform/templates/content_management/timely_course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>{% block title %}Courses{% endblock %}</title>
</head>
<body>
    {% block main %}
    <p class="text-danger">first to visit</p>
    {% for c in courses %}
    <a class="text-info ml-2" href="{{url_for('admin.timely_topics', c_id=c.id)}}">
        {{c.name}}
    </a> 
    <br>
    {% endfor %}
    {% endblock %}
</body>
</html>

learning_platform/templates/content_management/update_ai_content.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>{% block title %} AI content {% endblock %}</title>
</head>
<body>
    {% block main %}
    <div class="container text-center">
        <div class="row align-items-start text-center text-light">
            <form method="post" enctype=multipart/form-data>
                <input  type="hidden" name="csrf_token" value="{{ csrf_token() }}">
              
          <div class="col-4 fs-5 bg-info">
            <label for="file">Snippet:</label><br>
            <input type="file" id="file" name="file">
          </div>
          <div class="col-8 fs-3 bg-primary">
            <label for="description">Description:</label><br>
            <textarea id="desc" name="desc" rows="4" cols="50">{{vid['desc']}}</textarea>
          </div>
          <input type="submit" value="Submit">
        </form>
        </div>
      </div>
    {% endblock %}  
</body>
</html>

learning_platform/templates/content_management/update_display_text.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>{% block title %} Text Editor {% endblock %}</title>
</head>
<body>
    {% block main %}
    <div class="container text-center">
        <div class="row align-items-start text-center text-light">
            <form method="post">
            <input  type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <div class="col-8 fs-3 bg-primary">
            <label for="desc">explanation</label><br>
            <textarea id="desc" name="desc" rows="4" cols="50">{{vid['desc']}}</textarea>
          </div>
          <input type="submit" value="Translate">
        </form>
        
        </div>
      </div>
    {% endblock %}  
</body>
</html>

learning_platform/templates/content_management/update_original.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>{% block title %} Text {% endblock %}</title>
</head>
<body>
    {% block main %}
    <div class="container text-center">
        <div class="row align-items-start text-center text-light">
            <form method="post">
            <input  type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <div class="col-8 fs-3 bg-primary">
            <label for="desc">explanation</label><br>
            <textarea id="desc" name="desc" rows="8" cols="50">{{ desc }}</textarea>
          </div>
          <input type="submit" value="update">
        </form>
        
        </div>
      </div>
    {% endblock %}  
</body>
</html>

learning_platform/templates/content_management/user_courses.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>{% block title %} User Courses {% endblock %}</title>
</head>
<body>

    {% block main %}
    {% if courses %}
   {% for course in courses %}
   <div style="display: block; margin: 12px;">
    <p class="text-light">Name of Course: {{course.name}}</p>
    <p class="text-light">{{course.id}}</p>
    <p class="text-light">{{u_id}}</p>
    <a href="{{ url_for('admin.unenroll', u_id=u_id, c_id=course.id)}}">unenroll user</a>
    </div>
   
   {% endfor %}
   {% else %}
   <p style="background-color: whitesmoke;">
    User is not enrolled in any course
</p>
   {% endif %}
    {% endblock %}    
</body>
</html>

learning_platform/templates/content_management/user_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends "base.html" %}
    <title>{% block title %} Enter Email {% endblock %}</title>
</head>
<body>
    {% block main %}
    <div class="container text-center">
        <div class="row align-items-start text-center text-light">
            <form method="post">
            <input  type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <div class="col-8 fs-3 bg-primary">
            <label for="email">enter email</label><br>
            <input type="text" id="email" name="email"> 
          </div>
          <input type="submit" value="submit email">
        </form>
        
        </div>
      </div>
    {% endblock %}  
</body>
</html>